version: '3'
services:

  app1:
   build: .
   deploy:
    replicas: 5
   ports:
    - 81:80
    - 82:80
    - 83:80
    - 84:80
    - 85:80

  java:
    image: openjdk

  db:
    image: mongo
    ports:
     - 27017-27017
    env_file:
     - mongo.env
    depends_on:
     - java
