version: '3'
services:

  app:
   build: .
   ports:
    - 80:80

  java:
    image: openjdk

  db:
    image: mongo
    ports:
     - 27017-27017
    environment:
     - MONGO_INITDB_ROOT_USERNAME=admin
     - MONGO_INITDB_ROOT_PASSWORD=password
    depends_on:
     - java
