pipeline {
    agent { dockerfile { filename 'Task4/Dockerfile' } }
    stages {
        stage('Test') {
            steps {
                sh 'node --version'
            }
        }
    }
    post {
        always {
            archiveArtifacts artifacts: 'build/'
        }
    }
}
