pipeline {
    agent { dockerfile { filename 'Task4/Dockerfile' } }
    stages {
        stage('Test') {
            steps {
                sh 'service apache2 status'
            }
        }
    }
}
