node {
    agent { dockerfile { filename 'Task4/Dockerfile' } }
    checkout scm

    def customImage = docker.build("my-image:${env.BUILD_ID}")

    customImage.inside {
        sh 'make test'
    }
}
